---
regions:
  # san-francisco-bay_california:
  #   bbox:
  #     top: 38.719
  #     left: -123.640
  #     bottom: 36.791
  #     right: -121.025
  #   zoom_range: [0, 16]
  slovenia-test:
    bbox:
      top: 46.43305556
      left: 15.67583333
      bottom: 46.38861111
      right: 15.74166667 
    zoom_range: [14, 15]
outputs:
  - type: skadi
  - type: tiff
  - type: terrarium
  - type: normal
sources:
  - type: 'd96tm'
    uri: 'http://gis.arso.gov.si/lidar/otr/laz'
    fishnet_url: 'https://github.com/DavixDevelop/TerraLidar/raw/master/mapzen_data/lidar_fishnet_D96TM.zip'
logging:
  config: logging.example.config
cluster:
  queue:
    type: fake
store:
  type: file
  base_dir: 'render'
source_store:
  type: file
  base_dir: 'source'